version: '3'
services:
  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - TZ=Europe/Berlin
      - PGTZ=Europe/Berlin
    command: ["-c", "shared_buffers=1024MB"]
    profiles:
      - production
      - development
    volumes:
      # recreating container and starting reinits the db with files in this dir
      - ./database/init:/docker-entrypoint-initdb.d
      # use external volume to persist the db state
      - ./volumes/db-data:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT_EXT:5432
    restart: unless-stopped

  db-test:
    image: postgres:12-alpine
    container_name: db-test
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_TEST_DB
      - TZ=Europe/Berlin
      - PGTZ=Europe/Berlin
    profiles:
      - test
    volumes:
      # recreating container and starting reinits the db with files in this dir
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - $POSTGRES_PORT_EXT:5432
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - $ADMINER_PORT_EXT:8080
    restart: unless-stopped

  scrapyd:
    build:
      context: .
      dockerfile: scrapyd.Dockerfile
    ports:
      - 6800:6800
    env_file:
      - .env
    environment:
      - TZ=Europe/Berlin
    profiles:
      - production
      - development
    volumes:
      - ./volumes/scrapyd:/var/lib/scrapyd
      - /usr/local/lib/python3.9/dist-packages
    restart: unless-stopped
